package com.rcplus.wanted.models;

import lombok.Getter;

@Getter
public enum JobSpecialty {
    
    선택안함(JobField.ALL, "선택안함"),

    개발_전체(JobField.DEVELOPMENT, "개발 전체"),
    소프트웨어_엔지니어(JobField.DEVELOPMENT, "소프트웨어 엔지니어"),
    웹_개발자(JobField.DEVELOPMENT, "웹 개발자"),
    서버_개발자(JobField.DEVELOPMENT, "서버 개발자"),
    프론트엔드_개발자(JobField.DEVELOPMENT, "프론트엔드 개발자"),
    자바_개발자(JobField.DEVELOPMENT, "자바 개발자"),
    C_CPP_개발자(JobField.DEVELOPMENT, "C, C++ 개발자"),
    파이썬_개발자(JobField.DEVELOPMENT, "파이썬 개발자"),
    머신러닝_엔지니어(JobField.DEVELOPMENT, "머신러닝 엔지니어"),
    Node_JS_개발자(JobField.DEVELOPMENT, "Node.js 개발자"),
    데이터_엔지니어(JobField.DEVELOPMENT, "데이터 엔지니어"),
    안드로이드_개발자(JobField.DEVELOPMENT, "안드로이드 개발자"),
    DevOps_시스템_관리자(JobField.DEVELOPMENT, "DevOps/시스템 관리자"),
    iOS_개발자(JobField.DEVELOPMENT, "iOS 개발자"),
    개발_매니저(JobField.DEVELOPMENT, "개발 매니저"),
    QA_테스트_엔지니어(JobField.DEVELOPMENT, "QA, 테스트 엔지니어"),
    기술지원(JobField.DEVELOPMENT, "기술지원"),
    데이터_사이언티스트(JobField.DEVELOPMENT, "데이터 사이언티스트"),
    임베디드_개발자(JobField.DEVELOPMENT, "임베디드 개발자"),
    보안_엔지니어(JobField.DEVELOPMENT, "보안 엔지니어"),
    빅데이터_엔지니어(JobField.DEVELOPMENT, "빅데이터 엔지니어"),
    하드웨어_엔지니어(JobField.DEVELOPMENT, "하드웨어 엔지니어"),
    프로덕트_매니저(JobField.DEVELOPMENT, "프로덕트 매니저"),
    블록체인_플랫폼_엔지니어(JobField.DEVELOPMENT, "블록체인 플랫폼 엔지니어"),
    크로스플랫폼_앱_개발자(JobField.DEVELOPMENT, "크로스플랫폼 앱 개발자"),
    DBA(JobField.DEVELOPMENT, "DBA"),
    PHP_개발자(JobField.DEVELOPMENT, "PHP 개발자"),
    웹_퍼블리셔(JobField.DEVELOPMENT, "웹 퍼블리셔"),
    DOT_NET_개발자(JobField.DEVELOPMENT, ".NET 개발자"),
    영상_음성_엔지니어(JobField.DEVELOPMENT, "영상, 음성 엔지니어"),
    ERP_전문가(JobField.DEVELOPMENT, "ERP 전문가"),
    그래픽스_엔지니어(JobField.DEVELOPMENT, "그래픽스 엔지니어"),
    CTO(JobField.DEVELOPMENT, "CTO, Chief Technology Officer"),
    VR_엔지니어(JobField.DEVELOPMENT, "VR 엔지니어"),
    BI_엔지니어(JobField.DEVELOPMENT, "BI 엔지니어"),
    루비온레일즈_개발자(JobField.DEVELOPMENT, "루비온레일즈 개발자"),
    CIO(JobField.DEVELOPMENT, "CIO, Chief Information Officer"),

    경영_비즈니스_전체(JobField.BUSINESS, "경영/비즈니스 전체"),
    PM_PO(JobField.BUSINESS, "PM/PO"),
    사업개발_기획자(JobField.BUSINESS, "사업개발/기획자"),
    서비스_기획자(JobField.BUSINESS, "서비스 기획자"),
    전략_기획자(JobField.BUSINESS, "전략 기획자"),
    경영지원(JobField.BUSINESS, "경영지원"),
    운영_매니저(JobField.BUSINESS, "운영 매니저"),
    회계_경리(JobField.BUSINESS, "회계/경리"),
    데이터_분석가(JobField.BUSINESS, "데이터 분석가"),
    해외_사업개발_기획자(JobField.BUSINESS, "해외 사업개발/기획자"),
    총무(JobField.BUSINESS, "총무"),
    상품기획자_BM(JobField.BUSINESS, "상품기획자(BM)"),
    자금담당(JobField.BUSINESS, "자금담당"),
    컨설턴트(JobField.BUSINESS, "컨설턴트"),
    사무보조(JobField.BUSINESS, "사무보조"),
    오피스_관리(JobField.BUSINESS, "오피스 관리"),
    조직관리(JobField.BUSINESS, "조직관리"),
    정보보호_담당자(JobField.BUSINESS, "정보보호 담당자"),
    ISMS(JobField.BUSINESS, "ISMS(정보보호체계)"),
    구매담당(JobField.BUSINESS, "구매담당"),
    경영_혁신가(JobField.BUSINESS, "경영 혁신가"),
    비서(JobField.BUSINESS, "비서"),
    리스크_관리_전문가(JobField.BUSINESS, "리스크 관리 전문가"),
    지역_관리_매니저(JobField.BUSINESS, "지역 관리 매니저"),
    CFO(JobField.BUSINESS, "CFO, Chief Financial Officer"),
    전시_기획자(JobField.BUSINESS, "전시 기획자"),
    공연_기획자(JobField.BUSINESS, "공연 기획자"),
    COO(JobField.BUSINESS, "COO, Chief Operation Officer"),
    CSO(JobField.BUSINESS, "CSO, Chief Strategy Officer"),
    세미너_포럼_기획자(JobField.BUSINESS, "세미너/포럼 기획자"),
    CEO(JobField.BUSINESS, "CEO, Chief Execution Officer"),
    안내원(JobField.BUSINESS, "안내원"),
    지점장(JobField.BUSINESS, "지점장"),
    애자일코치(JobField.BUSINESS, "애자일코치"),
    사내_심리상담가(JobField.BUSINESS, "사내 심리상담가"),
    
    마케팅_광고_전체(JobField.MARKETING_ADVERTISING, "마케팅/광고 전체"),
    마케터(JobField.MARKETING_ADVERTISING, "마케터"),
    디지털_마케터(JobField.MARKETING_ADVERTISING, "디지털 마케터"),
    콘텐츠_마케터(JobField.MARKETING_ADVERTISING, "콘텐츠 마케터"),
    퍼포먼스_마케터(JobField.MARKETING_ADVERTISING, "퍼포먼스 마케터"),
    마케팅_전략_기획자(JobField.MARKETING_ADVERTISING, "마케팅 전략 기획자"),
    브랜드_마케터(JobField.MARKETING_ADVERTISING, "브랜드 마케터"),
    광고_기획자(JobField.MARKETING_ADVERTISING, "광고 기획자(AE)"),
    글로벌_마케팅(JobField.MARKETING_ADVERTISING, "글로벌 마케팅"),
    소셜_마케터(JobField.MARKETING_ADVERTISING, "소셜 마케터"),
    PR_전문가(JobField.MARKETING_ADVERTISING, "PR 전문가"),
    그로스_해커(JobField.MARKETING_ADVERTISING, "그로스 해커"),
    마케팅_디렉터(JobField.MARKETING_ADVERTISING, "마케팅 디렉터"),
    카피라이터(JobField.MARKETING_ADVERTISING, "카피라이터"),
    모바일마케팅(JobField.MARKETING_ADVERTISING, "모바일마케팅"),
    키워드광고(JobField.MARKETING_ADVERTISING, "키워드광고"),
    마켓_리서치(JobField.MARKETING_ADVERTISING, "마켓 리서치"),
    BTL_마케터(JobField.MARKETING_ADVERTISING, "BTL 마케터"),
    제휴(JobField.MARKETING_ADVERTISING, "제휴"),
    CMO(JobField.MARKETING_ADVERTISING, "CMO, Chief Marketing Officer"),
    ATL_마케터(JobField.MARKETING_ADVERTISING, "ATL 마케터"),
    CBO(JobField.MARKETING_ADVERTISING, "CBO, Chief Brand Officer"),
    Sports_전문가(JobField.MARKETING_ADVERTISING, "Sports 전문가"),

    디자인_전체(JobField.DESIGN, "디자인 전체"),
    UX_디자이너(JobField.DESIGN, "UX 디자이너"),
    UI_GUI_디자이너(JobField.DESIGN, "UI, GUI 디자이너"),
    웹_디자이너(JobField.DESIGN, "웹 디자이너"),
    그래픽_디자이너(JobField.DESIGN, "그래픽 디자이너"),
    모바일_디자이너(JobField.DESIGN, "모바일 디자이너"),
    광고_디자이너(JobField.DESIGN, "광고 디자이너"),
    제품_디자이너(JobField.DESIGN, "제품 디자이너"),
    BI_BX_디자이너(JobField.DESIGN, "BI/BX 디자이너"),
    영상_모션_디자이너(JobField.DESIGN, "영상, 모션 디자이너"),
    패키지_디자이너(JobField.DESIGN, "패키지 디자이너"),
    THREE_D_디자이너(JobField.DESIGN, "3D 디자이너"),
    아트_디렉터(JobField.DESIGN, "아트 디렉터"),
    TWO_D_디자이너(JobField.DESIGN, "2D 디자이너"),
    패션_디자이너(JobField.DESIGN, "패션 디자이너"),
    일러스트레이터(JobField.DESIGN, "일러스트레이터"),
    공간_디자이너(JobField.DESIGN, "공간 디자이너"),
    출판_편집_디자이너(JobField.DESIGN, "출판, 편집 디자이너"),
    산업_디자이너(JobField.DESIGN, "산업 디자이너"),
    인테리어_디자이너(JobField.DESIGN, "인테리어 디자이너"),
    캐릭터_디자이너(JobField.DESIGN, "캐릭터 디자이너"),
    VMD(JobField.DESIGN, "VMD"),
    전시_디자이너(JobField.DESIGN, "전시 디자이너"),
    패브릭_디자이너(JobField.DESIGN, "패브릭 디자이너"),
    가구_디자이너(JobField.DESIGN, "가구 디자이너"),
    조경_디자이너(JobField.DESIGN, "조경 디자이너"),

    영업_전체(JobField.SALES, "영업 전체"),
    기업영업(JobField.SALES, "기업영업"),
    외부영업(JobField.SALES, "외부영업"),
    영업_관리자(JobField.SALES, "영업 관리자"),
    기술영업(JobField.SALES, "기술영업"),
    주요고객사_담당자(JobField.SALES, "주요고객사 담당자"),
    해외영업(JobField.SALES, "해외영업"),
    솔루션_컨설턴트(JobField.SALES, "솔루션 컨설턴트"),
    내부영업(JobField.SALES, "내부영업"),
    미디어_세일즈(JobField.SALES, "미디어 세일즈"),
    고객성공매니저(JobField.SALES, "고객성공매니저"),
    세일즈_엔지니어(JobField.SALES, "세일즈 엔지니어"),
    의료기기_영업(JobField.SALES, "의료기기 영업"),
    제약_영업(JobField.SALES, "제약 영업"),

    고객서비스_리테일_전체(JobField.CUSTOMER_SERVICE_RETAIL, "고객서비스/리테일 전체"),
    MD(JobField.CUSTOMER_SERVICE_RETAIL, "MD"),
    서비스_운영(JobField.CUSTOMER_SERVICE_RETAIL, "서비스 운영"),
    CS_매니저(JobField.CUSTOMER_SERVICE_RETAIL, "CS 매니저"),
    리테일_MD(JobField.CUSTOMER_SERVICE_RETAIL, "리테일 MD"),
    CS_어드바이저(JobField.CUSTOMER_SERVICE_RETAIL, "CS 어드바이저"),
    패션_MD(JobField.CUSTOMER_SERVICE_RETAIL, "패션 MD"),
    매장_관리자(JobField.CUSTOMER_SERVICE_RETAIL, "매장 관리자"),
    인바운드_텔레마케터(JobField.CUSTOMER_SERVICE_RETAIL, "인바운드 텔레마케터"),
    CRM_전문가(JobField.CUSTOMER_SERVICE_RETAIL, "CRM 전문가"),
    매장점원(JobField.CUSTOMER_SERVICE_RETAIL, "매장점원"),
    가맹점_관리자(JobField.CUSTOMER_SERVICE_RETAIL, "가맹점 관리자"),
    아웃바운드_텔레마케터(JobField.CUSTOMER_SERVICE_RETAIL, "아웃바운드 텔레마케터"),
    이벤트_기획자(JobField.CUSTOMER_SERVICE_RETAIL, "이벤트 기획자"),
    AS_기술자(JobField.CUSTOMER_SERVICE_RETAIL, "AS 기술자"),
    리셉션(JobField.CUSTOMER_SERVICE_RETAIL, "리셉션"),
    비주얼머천다이저(JobField.CUSTOMER_SERVICE_RETAIL, "비주얼머천다이저"),
    여행_에이전트(JobField.CUSTOMER_SERVICE_RETAIL, "여행 에이전트"),
    헬스케어매니저(JobField.CUSTOMER_SERVICE_RETAIL, "헬스케어매니저"),
    승무원(JobField.CUSTOMER_SERVICE_RETAIL, "승무원"),
    플로리스트(JobField.CUSTOMER_SERVICE_RETAIL, "플로리스트"),
    피부관리사(JobField.CUSTOMER_SERVICE_RETAIL, "피부관리사"),
    헤어_디자이너(JobField.CUSTOMER_SERVICE_RETAIL, "헤어 디자이너"),
    미용사(JobField.CUSTOMER_SERVICE_RETAIL, "미용사"),
    애견_미용사(JobField.CUSTOMER_SERVICE_RETAIL, "애견 미용사"),

    미디어_전체(JobField.MEDIA, "미디어 전체"),
    콘텐츠_크리에이터(JobField.MEDIA, "콘텐츠 크리에이터"),
    PD(JobField.MEDIA, "PD"),
    영상_편집가(JobField.MEDIA, "영상 편집가"),
    비디오_제작(JobField.MEDIA, "비디오 제작"),
    에디터(JobField.MEDIA, "에디터"),
    연예_엔터테인먼트(JobField.MEDIA, "연예, 엔터테인먼트"),
    작가(JobField.MEDIA, "작가"),
    통번역(JobField.MEDIA, "통/번역"),
    사진작가(JobField.MEDIA, "사진작가"),
    라이센스_관리자(JobField.MEDIA, "라이센스 관리자"),
    출판_기획자(JobField.MEDIA, "출판 기획자"),
    큐레이터(JobField.MEDIA, "큐레이터"),
    저널리스트(JobField.MEDIA, "저널리스트"),
    음향_엔지니어(JobField.MEDIA, "음향 엔지니어"),
    리포터(JobField.MEDIA, "리포터"),

    엔지니어링_설계_전체(JobField.ENGINEERING, "엔지니어링/설계 전체"),
    전자_엔지니어(JobField.ENGINEERING, "전자 엔지니어"),
    기계_엔지니어(JobField.ENGINEERING, "기계 엔지니어"),
    로봇_자동화(JobField.ENGINEERING, "로봇/자동화"),
    전기_엔지니어(JobField.ENGINEERING, "전기 엔지니어"),
    CAD_3D_설계자(JobField.ENGINEERING, "CAD/3D 설계자"),
    제품_엔지니어(JobField.ENGINEERING, "제품 엔지니어"),
    전자기계_공학자(JobField.ENGINEERING, "전자기계 공학자"),
    제어_엔지니어(JobField.ENGINEERING, "제어 엔지니어"),
    QA_엔지니어(JobField.ENGINEERING, "QA 엔지니어"),
    설비_엔지니어(JobField.ENGINEERING, "설비 엔지니어"),
    장비_엔지니어(JobField.ENGINEERING, "장비 엔지니어"),
    프로젝트_엔지니어(JobField.ENGINEERING, "프로젝트 엔지니어"),
    공정_엔지니어(JobField.ENGINEERING, "공정 엔지니어"),
    자동차_엔지니어(JobField.ENGINEERING, "자동차 엔지니어"),
    도면_담당자(JobField.ENGINEERING, "도면 담당자"),
    산업_엔지니어(JobField.ENGINEERING, "산업 엔지니어"),
    QC_엔지니어(JobField.ENGINEERING, "QC 엔지니어"),
    건설_엔지니어(JobField.ENGINEERING, "건설 엔지니어"),
    도면_작성가(JobField.ENGINEERING, "도면 작성가"),
    인허가_담당_엔지니어(JobField.ENGINEERING, "인허가 담당 엔지니어"),
    항공우주_공학자(JobField.ENGINEERING, "항공우주 공학자"),
    화학공학_엔지니어(JobField.ENGINEERING, "화학공학 엔지니어"),
    환경_엔지니어(JobField.ENGINEERING, "환경 엔지니어"),
    RF_엔지니어(JobField.ENGINEERING, "RF 엔지니어"),
    토목기사(JobField.ENGINEERING, "토목기사"),
    환경_안전기사(JobField.ENGINEERING, "환경 안전기사"),
    지리정보시스템(JobField.ENGINEERING, "지리정보시스템"),
    보건안전_엔지니어(JobField.ENGINEERING, "보건안전 엔지니어"),
    구조공학_엔지니어(JobField.ENGINEERING, "구조공학 엔지니어"),
    보일러_엔지니어(JobField.ENGINEERING, "보일러 엔지니어"),
    시운전_엔지니어(JobField.ENGINEERING, "시운전 엔지니어"),
    플랜트_엔지니어(JobField.ENGINEERING, "플랜트 엔지니어"),
    전자계전_엔지니어(JobField.ENGINEERING, "전자계전 엔지니어"),
    고압설계_엔지니어(JobField.ENGINEERING, "고압설계 엔지니어"),
    생산공학_엔지니어(JobField.ENGINEERING, "생산공학 엔지니어"),
    재료공학자(JobField.ENGINEERING, "재료공학자"),
    사업수주_엔지니어(JobField.ENGINEERING, "사업수주 엔지니어"),
    회전기계_엔지니어(JobField.ENGINEERING, "회전기계 엔지니어"),
    농업_공학자(JobField.ENGINEERING, "농업 공학자"),
    유전_공학자(JobField.ENGINEERING, "유전 공학자"),
    생물의학자(JobField.ENGINEERING, "생물의학자"),
    세라믹_엔지니어(JobField.ENGINEERING, "세라믹 엔지니어"),
    시추_엔지니어(JobField.ENGINEERING, "시추 엔지니어"),
    소방안전_기술자(JobField.ENGINEERING, "소방안전 기술자"),
    지리학자(JobField.ENGINEERING, "지리학자"),
    지질공학자(JobField.ENGINEERING, "지질공학자"),
    IC_엔지니어(JobField.ENGINEERING, "I&C 엔지니어"),
    해양공학자(JobField.ENGINEERING, "해양공학자"),
    금속_공학자(JobField.ENGINEERING, "금속 공학자"),
    광산_기술자(JobField.ENGINEERING, "광산 기술자"),
    광산_안전_기술자(JobField.ENGINEERING, "광산 안전 기술자"),
    선박_공학자(JobField.ENGINEERING, "선박 공학자"),
    원자력_에너지(JobField.ENGINEERING, "원자력/에너지"),
    석유공학_엔지니어(JobField.ENGINEERING, "석유공학 엔지니어"),
    배관설계_엔지니어(JobField.ENGINEERING, "배관설계 엔지니어"),
    플라스틱_엔지니어(JobField.ENGINEERING, "플라스틱 엔지니어"),
    저수처리_엔지니어(JobField.ENGINEERING, "저수처리 엔지니어"),
    터빈공학자(JobField.ENGINEERING, "터빈공학자"),

    게임_제작_전체(JobField.GAMES, "게임 제작 전체"),
    게임_그래픽_디자이너(JobField.GAMES, "게임 그래픽 디자이너"),
    게임_아티스트(JobField.GAMES, "게임 아티스트"),
    게임_기획자(JobField.GAMES, "게임 기획자"),
    게임_클라이언트_개발자(JobField.GAMES, "게임 클라이언트 개발자"),
    유니티_개발자(JobField.GAMES, "유니티 개발자"),
    모바일_게임_개발자(JobField.GAMES, "모바일 게임 개발자"),
    게임_서버_개발자(JobField.GAMES, "게임 서버 개발자"),
    언리얼_개발자(JobField.GAMES, "언리얼 개발자"),
    게임운영자(JobField.GAMES, "게임운영자(GM)"),

    HR_전체(JobField.HR, "HR 전체"),
    인사담당(JobField.HR, "인사담당"),
    조직문화(JobField.HR, "조직문화"),
    리크루터(JobField.HR, "리크루터"),
    평가_보상(JobField.HR, "평가/보상"),
    HRD(JobField.HR, "HRD"),
    급여담당(JobField.HR, "급여담당"),
    HRBP(JobField.HR, "HRBP"),
    노무_노사(JobField.HR, "노무/노사"),
    헤드헌터(JobField.HR, "헤드헌터"),
    HR_컨설턴트(JobField.HR, "HR 컨설턴트"),
    사내_강사(JobField.HR, "사내 강사"),
    기술_교육(JobField.HR, "기술 교육"),
    E러닝(JobField.HR, "E-러닝"),
    교사(JobField.HR, "교사"),
    교수(JobField.HR, "교수"),

    금융_전체(JobField.FINANCE, "금융 전체"),
    재무_담당자(JobField.FINANCE, "재무 담당자"),
    회계담당(JobField.FINANCE, "회계담당"),
    투자_증권(JobField.FINANCE, "투자/증권"),
    IR(JobField.FINANCE, "IR"),
    재무_분석가(JobField.FINANCE, "재무 분석가"),
    내부통제_담당자(JobField.FINANCE, "내부통제 담당자"),
    애널리스트(JobField.FINANCE, "애널리스트"),
    자산운용가(JobField.FINANCE, "자산운용가"),
    공인회계사(JobField.FINANCE, "공인회계사"),
    부동산_자산_관리사(JobField.FINANCE, "부동산 자산 관리사"),
    트레이더(JobField.FINANCE, "트레이더"),
    준법감시인(JobField.FINANCE, "준법감시인"),
    부동산_중개사(JobField.FINANCE, "부동산 중개사"),
    세무사(JobField.FINANCE, "세무사"),
    금융공학자(JobField.FINANCE, "금융공학자"),
    자산관리사(JobField.FINANCE, "자산관리사"),
    투자은행가(JobField.FINANCE, "투자은행가"),
    손해_사정관(JobField.FINANCE, "손해 사정관"),
    청구_담당(JobField.FINANCE, "청구 담당자"),
    보험_에이전트(JobField.FINANCE, "보험 에이전트"),
    계리사(JobField.FINANCE, "계리사"),
    언더라이터(JobField.FINANCE, "언더라이터"),
    감정평가사(JobField.FINANCE, "감정평가사"),

    제조_생산_전체(JobField.MANFACTURE, "제조/생산 전체"),
    품질_관리자(JobField.MANFACTURE, "품질 관리자"),
    생산_관리자(JobField.MANFACTURE, "생산 관리자"),
    자재관리_구매(JobField.MANFACTURE, "자재관리/구매"),
    기계_설비_설계(JobField.MANFACTURE, "기계/설비/설계"),
    제조_엔지니어(JobField.MANFACTURE, "제조 엔지니어"),
    섬유_의류_패션(JobField.MANFACTURE, "섬유/의류/패션"),
    공정_관리자(JobField.MANFACTURE, "공정 관리자"),
    생산직_종사자(JobField.MANFACTURE, "생산직 종사자"),
    안전_관리자(JobField.MANFACTURE, "안전 관리자"),
    기계제작_기술자(JobField.MANFACTURE, "기계제작 기술자"),
    반도체_디스플레이(JobField.MANFACTURE, "반도체/디스플레이"),
    조립_기술자(JobField.MANFACTURE, "조립 기술자"),
    화학자(JobField.MANFACTURE, "화학자"),
    제조_테스트_엔지니어(JobField.MANFACTURE, "제조 테스트 엔지니어"),

    물류_무역_전체(JobField.SHIPPING_TRADES, "물류/무역 전체"),
    물류담당(JobField.SHIPPING_TRADES, "물류담당"),
    입출고_관리자(JobField.SHIPPING_TRADES, "입/출고 관리자"),
    유통_관리자(JobField.SHIPPING_TRADES, "유통 관리자"),
    물류_분석가(JobField.SHIPPING_TRADES, "물류 분석가"),
    수출입사무(JobField.SHIPPING_TRADES, "수출입사무"),
    무역사무(JobField.SHIPPING_TRADES, "무역사무"),
    바이어관리_상담_개발(JobField.SHIPPING_TRADES, "바이어관리/상담/개발"),
    배송담당(JobField.SHIPPING_TRADES, "배송담당"),
    운성_관리자(JobField.SHIPPING_TRADES, "운성 관리자"),
    웨어하우스(JobField.SHIPPING_TRADES, "웨어하우스"),
    지게차_운전사(JobField.SHIPPING_TRADES, "지게차 운전사"),
    화물트럭_운전사(JobField.SHIPPING_TRADES, "화물트럭 운전사"),
    해운_해양_운송(JobField.SHIPPING_TRADES, "해운/해양 운송"),
    관세사(JobField.SHIPPING_TRADES, "관세사"),
    운전기사(JobField.SHIPPING_TRADES, "운전기사"),
    항공_운송(JobField.SHIPPING_TRADES, "항공 운송"),
    원산지관리사(JobField.SHIPPING_TRADES, "원산지관리사"),
    디젤_정비공(JobField.SHIPPING_TRADES, "디젤 정비공"),
    운행_관리원(JobField.SHIPPING_TRADES, "운행 관리원"),
    선적_발송_사무원(JobField.SHIPPING_TRADES, "선적, 발송 사무원"),
    보세사(JobField.SHIPPING_TRADES, "보세사"),
    행해사(JobField.SHIPPING_TRADES, "행해사"),
    기관사(JobField.SHIPPING_TRADES, "기관사");
    
    private String name;
    private JobField field;

    JobSpecialty(JobField field, String name) {
        this.field = field;
        this.name = name;
    }
}
